# Generated by Django 4.1.1 on 2022-09-10 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import jobs.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_middle_about', models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension])),
                ('text_about', models.TextField(blank=True, default='', max_length=1000)),
                ('text_about_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AboutBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_about', models.FileField(blank=True, upload_to='background/services/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(db_index=True, default='', max_length=255, unique=True)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_about_index', models.TextField(blank=True, default='', max_length=1000)),
                ('text_about_index_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('text_index', models.TextField(blank=True, default='', max_length=1000)),
                ('text_index_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_volunteer', models.FileField(upload_to='background/volunteer/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.FileField(blank=True, default='', upload_to='blogs/backgrounds/', validators=[jobs.validators.validate_image_extension])),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('tutorial_Video', embed_video.fields.EmbedVideoField()),
                ('comment', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('title_ar', models.CharField(blank=True, default='', max_length=300)),
                ('view', models.CharField(blank=True, default='', max_length=300)),
                ('desc1', models.CharField(blank=True, default='', max_length=200)),
                ('desc1_ar', models.CharField(blank=True, default='', max_length=40000)),
                ('desc2', models.TextField(blank=True, default='', max_length=40000)),
                ('desc2_ar', models.TextField(blank=True, default='', max_length=40000)),
                ('blank', models.CharField(blank=True, default='', max_length=600)),
                ('blank_ar', models.CharField(blank=True, default='', max_length=600)),
                ('desc3', models.TextField(blank=True, default='', max_length=40000)),
                ('desc3_ar', models.TextField(blank=True, default='', max_length=40000)),
                ('desc4', models.TextField(blank=True, default='', max_length=40000)),
                ('desc4_ar', models.TextField(blank=True, default='', max_length=40000)),
                ('desc5', models.TextField(blank=True, default='', max_length=40000)),
                ('desc5_ar', models.TextField(blank=True, default='', max_length=40000)),
                ('desc6', models.TextField(blank=True, default='', max_length=40000)),
                ('desc6_ar', models.TextField(blank=True, default='', max_length=40000)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle_ar', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle_desc1', models.CharField(blank=True, default='', max_length=40000)),
                ('subtitle_desc1_ar', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle_desc2', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle_desc2_ar', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle_desc3', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle_desc3_ar', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle_desc4', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle_desc4_ar', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle2', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle2_ar', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle2_desc1', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle2_desc1_ar', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle2_desc2', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle2_desc2_ar', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle2_desc3', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle2_desc3_ar', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle2_desc4', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle2_desc4_ar', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle3', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle3_ar', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle3_desc1', models.CharField(blank=True, default='', max_length=4000)),
                ('subtitle3_desc1_ar', models.CharField(blank=True, default='', max_length=4000)),
                ('image_two', models.FileField(blank=True, default='', upload_to='blogs/backgrounds', validators=[jobs.validators.validate_image_extension])),
                ('image_three', models.FileField(blank=True, default='', upload_to='blogs/backgrounds', validators=[jobs.validators.validate_image_extension])),
                ('image_four', models.FileField(blank=True, default='', upload_to='blogs/backgrounds', validators=[jobs.validators.validate_image_extension])),
                ('image_five', models.FileField(blank=True, default='', upload_to='blogs/backgrounds', validators=[jobs.validators.validate_image_extension])),
                ('image_six', models.FileField(blank=True, default='', upload_to='blogs/backgrounds', validators=[jobs.validators.validate_image_extension])),
                ('image_seven', models.FileField(blank=True, default='', upload_to='blogs/backgrounds', validators=[jobs.validators.validate_image_extension])),
                ('image_eight', models.FileField(blank=True, default='', upload_to='blogs/backgrounds', validators=[jobs.validators.validate_image_extension])),
                ('image_nine', models.FileField(blank=True, default='', upload_to='blogs/backgrounds', validators=[jobs.validators.validate_image_extension])),
                ('image_ten', models.FileField(blank=True, default='', upload_to='blogs/backgrounds', validators=[jobs.validators.validate_image_extension])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
