# Generated by Django 4.0.4 on 2022-09-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_blog_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='view',
        ),
    ]
