# Generated by Django 4.0.4 on 2022-09-14 19:37

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_blog_comment_remove_blog_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tutorial_Video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=''),
        ),
    ]
