# Generated by Django 4.0.4 on 2022-09-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_blog_tutorial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc1_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
