# Generated by Django 4.0.4 on 2022-09-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_blog_desc1_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_eight',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_five',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_nine',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_seven',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_six',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_ten',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_two',
        ),
    ]
