# Generated by Django 4.0.4 on 2022-09-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_blog_image_eight_remove_blog_image_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitle2_desc1',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle2_desc1_ar',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle2_desc2',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle2_desc2_ar',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle2_desc3',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle2_desc3_ar',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle2_desc4',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle2_desc4_ar',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle3_desc1',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle3_desc1_ar',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_desc2',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_desc2_ar',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_desc3',
            field=models.CharField(blank=True, default='', max_length=400000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_desc3_ar',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_desc4',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_desc4_ar',
            field=models.CharField(blank=True, default='', max_length=40000),
        ),
    ]
