# Generated by Django 4.0.4 on 2022-09-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_blog_subtitle2_desc1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBackgroundImage',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_about',
        ),
        migrations.RemoveField(
            model_name='about',
            name='text_about_ar',
        ),
    ]
