# Generated by Django 4.0.4 on 2022-09-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_delete_aboutbackgroundimage_remove_about_text_about_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
