# Generated by Django 4.0.4 on 2022-09-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authors',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='authors_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
