# Generated by Django 4.0.4 on 2022-09-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_blog_authors_blog_authors_ar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='subtitle2_desc4',
            new_name='subtitle4_desc1',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subtitle2_desc4_ar',
            new_name='subtitle4_desc1_ar',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subtitle_desc3_ar',
            new_name='subtitle4_desc2',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subtitle_desc4',
            new_name='subtitle4_desc2_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_desc3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_desc4_ar',
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle4',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle4_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
